// apps/nextjs/app/[slug]/SauceModal.tsx
'use client';

import { useEffect, useRef, useState } from 'react';
import type { Item } from '@bench/data';

interface SauceModalProps {
  item: Item | null;
  onChoose: (sauceId: string) => void;
  onCancel: () => void;
}

type PieModalElement = HTMLElement & { isOpen?: boolean };

export default function SauceModal({ item, onChoose, onCancel }: SauceModalProps) {
  const modalRef = useRef<PieModalElement | null>(null);
  const [selected, setSelected] = useState<string>('');

  useEffect(() => {
    if (item) {
      setSelected(item.sauces[0]?.id ?? '');
    }
  }, [item]);

  // Pie modal uses the `isOpen` prop; sync it with our React state.
  useEffect(() => {
    const el = modalRef.current;
    if (!el) return;
    el.isOpen = item !== null;
  }, [item]);

  useEffect(() => {
    const el = modalRef.current;
    if (!el) return;
    const onClose = () => onCancel();
    el.addEventListener('pie-modal-close', onClose);
    el.addEventListener('pie-modal-back', onClose);
    return () => {
      el.removeEventListener('pie-modal-close', onClose);
      el.removeEventListener('pie-modal-back', onClose);
    };
  }, [onCancel]);

  const handleConfirm = () => {
    if (selected) onChoose(selected);
  };

  // Render the modal element even when no item is active, so the custom
  // element is present in the DOM and Pie's own focus management can run.
  return (
    <pie-modal
      ref={modalRef as unknown as React.Ref<HTMLElement>}
      heading={item ? `Add ${item.name}` : 'Choose your sauce'}
      heading-level="h2"
      size="small"
      is-dismissible="true"
    >
      {item ? (
        <form
          onSubmit={(event) => {
            event.preventDefault();
            handleConfirm();
          }}
        >
          <p className="modal__description">{item.description}</p>
          <pie-radio-group
            name="sauce"
            value={selected}
            onChange={(event: React.ChangeEvent<HTMLElement>) => {
              const target = event.target as HTMLInputElement;
              setSelected(target.value);
            }}
          >
            {item.sauces.map((sauce) => (
              <pie-radio
                key={sauce.id}
                value={sauce.id}
                {...(selected === sauce.id ? { checked: true } : {})}
              >
                {sauce.name}
                {sauce.surcharge > 0 ? ` (+\u00a3${(sauce.surcharge / 100).toFixed(2)})` : ''}
              </pie-radio>
            ))}
          </pie-radio-group>
          <div slot="footer" className="modal__footer">
            <pie-button type="submit" variant="primary" onClick={handleConfirm}>
              Add to basket
            </pie-button>
            <pie-button type="button" variant="ghost" onClick={onCancel}>
              Cancel
            </pie-button>
          </div>
        </form>
      ) : null}
    </pie-modal>
  );
}

// apps/sveltekit/src/routes/[slug]/SauceModal.svelte
<script lang="ts">
  import type { Item } from '@bench/data';

  interface Props {
    item: Item | null;
    onChoose: (sauceId: string) => void;
    onCancel: () => void;
  }
  let { item, onChoose, onCancel }: Props = $props();

  let selected = $state('');
  let modalEl: HTMLElement | undefined = $state();

  // Sync internal selection state when the active item changes.
  $effect(() => {
    if (item) {
      selected = item.sauces[0]?.id ?? '';
    }
  });

  // Mirror our open/closed state into Pie modal's `isOpen` property.
  $effect(() => {
    if (modalEl) {
      // The Pie modal is a Lit element with an isOpen property.
      (modalEl as HTMLElement & { isOpen?: boolean }).isOpen = item !== null;
    }
  });

  const handleConfirm = (event: Event) => {
    event.preventDefault();
    if (selected) onChoose(selected);
  };
</script>

<pie-modal
  bind:this={modalEl}
  heading={item ? `Add ${item.name}` : 'Choose your sauce'}
  heading-level="h2"
  size="small"
  is-dismissible="true"
  onpie-modal-close={onCancel}
  onpie-modal-back={onCancel}
>
  {#if item}
    <form onsubmit={handleConfirm}>
      <p class="modal__description">{item.description}</p>
      <pie-radio-group
        name="sauce"
        value={selected}
        onchange={(event: Event) => (selected = (event.target as HTMLInputElement).value)}
      >
        {#each item.sauces as sauce (sauce.id)}
          <pie-radio value={sauce.id} checked={selected === sauce.id}>
            {sauce.name}{#if sauce.surcharge > 0} (+{`\u00a3${(sauce.surcharge / 100).toFixed(2)}`}){/if}
          </pie-radio>
        {/each}
      </pie-radio-group>
      <div slot="footer" class="modal__footer">
        <pie-button type="submit" variant="primary" onclick={handleConfirm}>Add to basket</pie-button>
        <pie-button type="button" variant="ghost" onclick={onCancel}>Cancel</pie-button>
      </div>
    </form>
  {/if}
</pie-modal>
